name: Deploy beta.vishalmerani.com

on:
  push:
    branches: [main]
    paths:
      - 'beta/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy beta folder to beta-site branch
        run: |
          mkdir beta-publish
          cp -r beta/* beta-publish/
          cd beta-publish
          git init
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout -b beta-site
          echo 'beta.vishalmerani.com' > CNAME
          git add .
          git commit -m "Deploy beta"
          git push --force https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} beta-site
